#%% 
import pandas as pd 
import numpy as np 
from sklearn.preprocessing import  OneHotEncoder

# Extraindo Ano e Mês de vencimento das faturas
def extrair_datas(data): 
    
    data['ANO_VENCIMENTO'] = data['DATA_VENCIMENTO'].dt.year
    data['MES_VENCIMENTO'] = data['DATA_VENCIMENTO'].dt.month
    data['TRIMESTRE'] = data['DATA_VENCIMENTO'].dt.quarter

    return data 
#%%[markdown]
# Vamos criar lags para faciliatar o nosso modelo a identificar padrões das faturas. 
# Como queremos prever o valor futuro da próxima fatura, é interessante que o modelo saiba qual foi o valor passado desta fatura,
# e para isso utilizaremos valores passados das faturas de cada matícula.  
#%%
def criar_lags_por_matricula(data, col, id_col, max_lag=5):
    """
    Cria colunas de lag para séries temporais agrupadas por um identificador.
    
    Parameters:
    - data (pd.DataFrame): DataFrame contendo os dados.
    - col (str): Nome da coluna para a qual os lags serão criados.
    - id_col (str): Nome da coluna de identificação para agrupar os dados (ex.: matrícula).
    - max_lag (int): Número máximo de lags a serem criados.
    
    Returns:
    - pd.DataFrame: DataFrame com as colunas de lag adicionadas.
    """
    def criar_lags_grupo(grupo):
        for lag in range(1, max_lag + 1):
            grupo[f'{col}_lag{lag}'] = grupo[col].shift(lag)
        return grupo
    
    # Aplica a função de lags para cada grupo
    data = data.groupby(id_col).apply(criar_lags_grupo)
    
    # Remove valores nulos gerados pelos lags
    data = data.dropna().reset_index(drop=True)
    
    return data



def adicionar_regiao_e_onehot(data: pd.DataFrame) -> pd.DataFrame:
    """Adiciona uma coluna 'REGIÃO' ao DataFrame com base na coluna 'BAIRRO',
    garantindo que todos os nomes de bairros estejam em letras maiúsculas.
    Também aplica One-Hot Encoding na coluna 'REGIÃO'.

    Args:
        data (pd.DataFrame): DataFrame contendo a coluna 'BAIRRO'.

    Returns:
        pd.DataFrame: DataFrame com a nova coluna 'REGIÃO' e as colunas one-hot correspondentes.
    """
    # Garantindo que todos os bairros estejam em letras maiúsculas
    data['BAIRRO'] = data['BAIRRO'].str.upper()

    # Dicionário de mapeamento de bairros para regionais
    mapeamento_regioes = {
    'AARÃO REIS': 'NORTE',
    'ACABA MUNDO': 'CENTRO-SUL',
    'ACAIACA': 'NORDESTE',
    'ADEMAR MALDONADO': 'BARREIRO',
    'AEROPORTO': 'PAMPULHA',
    'ÁGUAS CLARAS': 'BARREIRO',
    'ALÍPIO DE MELO': 'PAMPULHA',
    'ALPES': 'OESTE',
    'ALTA TENSÃO': 'BARREIRO',
    'ALTO BARROCA': 'OESTE',
    'ALTO CAIÇARAS': 'NOROESTE',
    'ALTO DAS ANTENAS':'BARREIRO',
    'ALTO DOS PINHEIROS': 'NOROESTE',
    'ALTO VERA CRUZ': 'LESTE',
    'ÁLVARO CAMARGOS': 'NOROESTE',
    'AMBROSINA': 'OESTE',
    'ANCHIETA': 'CENTRO-SUL',
    'ANDIROBA': 'NORDESTE',
    'ANTÔNIO RIBEIRO DE ABREU': 'NORDESTE',
    'APARECIDA': 'NOROESTE',
    'APARECIDA SÉTIMA SEÇÃO': 'NOROESTE',
    'ÁPIA': 'CENTRO-SUL',
    'APOLÔNIA': 'VENDA NOVA',
    'ARAGUAIA': 'BARREIRO',
    'ÁTILA DE PAIVA': 'BARREIRO',
    'BACURAU': 'NORTE',
    'BAIRRO DAS INDÚSTRIAS I': 'BARREIRO',
    'BAIRRO DAS INDÚSTRIAS II': 'OESTE',
    'BAIRRO NOVO DAS INDÚSTRIAS': 'BARREIRO',
    'BALEIA': 'LESTE',
    'BANDEIRANTES': 'PAMPULHA',
    'BARÃO HOMEM DE MELO I': 'OESTE',
    'BARÃO HOMEM DE MELO III': 'OESTE',
    'BARÃO HOMEM DE MELO IV': 'OESTE',
    'BARREIRO': 'BARREIRO',
    'BARRO PRETO': 'CENTRO-SUL',
    'BARROCA': 'OESTE',
    'BEIJA FLOR': 'NORDESTE',
    'BEIRA-LINHA': 'NORDESTE',
    'BELA VITÓRIA': 'NORDESTE',
    'BELÉM': 'LESTE',
    'BELMONTE': 'NORDESTE',
    'BELVEDERE': 'CENTRO-SUL',
    'BERNADETE': 'BARREIRO',
    'BETÂNIA': 'OESTE',
    'BIQUINHAS': 'NORTE',
     'BISPO DE MAURA': 'PAMPULHA',
    'BOA ESPERANÇA': 'NORDESTE',
     'BOA UNIÃO I': 'NORTE',
    'BOA UNIÃO II': 'NORTE',
    'BOA VIAGEM': 'CENTRO-SUL',
     'BOA VISTA': 'LESTE',
    'BOM JESUS': 'NOROESTE',
    'BONFIM': 'NOROESTE',
    'BONSUCESSO': 'BARREIRO',
    'BRASIL INDUSTRIAL': 'BARREIRO',
    'BRAÚNAS': 'PAMPULHA',
    'BURITIS': 'OESTE',
    'CABANA DO PAI TOMÁS': 'OESTE',
    'CACHOEIRINHA': 'NORDESTE',
    'CAETANO FURQUIM': 'LESTE',
    'CAIÇARA-ADELAIDE': 'NOROESTE',
    'CAIÇARAS': 'NOROESTE',
    'CALAFATE': 'OESTE',
    'CALIFORNIA': 'NOROESTE',
    'CAMARGOS': 'OESTE',
    'CAMPO ALEGRE': 'NORTE',
    'CAMPONESA I': 'LESTE',
     'CAMPONESA III': 'LESTE',
    'CAMPUS UFMG': 'PAMPULHA',
    'CANAÃ': 'VENDA NOVA',
    'CANADÁ': 'NORDESTE',
    'CANDELÁRIA': 'VENDA NOVA',
    'CAPITÃO EDUARDO': 'NORDESTE',
     'CARDOSO': 'BARREIRO',
    'CARLOS PRATES': 'NOROESTE',
    'CARMO': 'CENTRO-SUL',
    'CASA BRANCA': 'LESTE',
    'CASTANHEIRA': 'BARREIRO',
    'CASTELO': 'PAMPULHA',
    'CDI JATOBÁ': 'BARREIRO',
     'CENÁCULO': 'VENDA NOVA',
    'CENTRO': 'CENTRO-SUL',
    'CÉU AZUL': 'VENDA NOVA',
    'CHÁCARA LEONINA': 'OESTE',
     'CIDADE JARDIM': 'CENTRO-SUL',
    'CIDADE JARDIM TAQUARIL': 'LESTE',
    'CIDADE NOVA': 'NORDESTE',
     'CINQÜENTENÁRIO': 'OESTE',
    'COLÉGIO BATISTA': 'NORDESTE',
    'COMITECO': 'CENTRO-SUL',
    'CONCÓRDIA': 'NORDESTE',
    'CÔNEGO PINHEIRO': 'LESTE',
     'CÔNEGO PINHEIRO A': 'LESTE',
    'CONFISCO': 'PAMPULHA',
    'CONJUNTO BONSUCESSO': 'BARREIRO',
     'CONJUNTO CALIFORNIA I': 'NOROESTE',
    'CONJUNTO CALIFORNIA II': 'NOROESTE',
    'CONJUNTO CAPITÃO EDUARDO': 'NORDESTE',
    'CONJUNTO CELSO MACHADO': 'PAMPULHA',
     'CONJUNTO FLORAMAR': 'NORTE',
    'CONJUNTO JARDIM FILADELFIA': 'NOROESTE',
    'CONJUNTO JATOBÁ': 'BARREIRO',
    'CONJUNTO LAGOA': 'PAMPULHA',
    'CONJUNTO MINASCAIXA': 'VENDA NOVA',
    'CONJUNTO NOVO DOM BOSCO': 'NOROESTE',
     'CONJUNTO PAULO VI': 'NORDESTE',
    'CONJUNTO PROVIDÊNCIA': 'NORTE',
    'CONJUNTO SANTA MARIA': 'CENTRO-SUL',
    'CONJUNTO SÃO FRANCISCO DE ASSIS': 'PAMPULHA',
    'CONJUNTO SERRA VERDE': 'VENDA NOVA',
    'CONJUNTO TAQUARIL': 'LESTE',
     'COPACABANA': 'VENDA NOVA',
    'COQUEIROS': 'NOROESTE',
    'CORAÇÃO DE JESUS': 'CENTRO-SUL',
     'CORAÇÃO EUCARÍSTICO': 'NOROESTE',
    'CORUMBIARA': 'BARREIRO',
    'CRUZEIRO': 'CENTRO-SUL',
    'CUSTODINHA': 'OESTE',
    'DELTA': 'NOROESTE',
    'DIAMANTE': 'BARREIRO',
    'DISTRITO INDUSTRIAL DO JATOBÁ': 'BARREIRO',
    'DOM BOSCO': 'NOROESTE',
    'DOM CABRAL': 'NOROESTE',
     'DOM JOAQUIM': 'NORDESTE',
    'DOM SILVÉRIO': 'NORDESTE',
     'DONA CLARA': 'PAMPULHA',
    'ENGENHO NOGUEIRA': 'PAMPULHA',
    'ERMELINDA': 'NOROESTE',
    'ERNESTO DO NASCIMENTO': 'BARREIRO',
    'ESPERANÇA': 'BARREIRO',
    'ESPLANADA': 'LESTE',
    'ESTORIL': 'OESTE',
    'ESTRELA': 'CENTRO-SUL',
    'ESTRELA DO ORIENTE': 'OESTE',
    'ETELVINA CARNEIRO': 'NORTE',
    'EUROPA': 'VENDA NOVA',
    'EYMARD': 'NORDESTE',
     'FAZENDINHA': 'CENTRO-SUL',
    'FERNÃO DIAS': 'NORDESTE',
    'FLAMENGO': 'VENDA NOVA',
    'FLÁVIO DE OLIVEIRA': 'BARREIRO',
    'FLÁVIO MARQUES LISBOA': 'BARREIRO',
    'FLORAMAR': 'NORTE',
    'FLORESTA': 'CENTRO-SUL',
    'FREI LEOPOLDO': 'NORTE',
    'FUNCIONÁRIOS': 'CENTRO-SUL',
     'GAMELEIRA': 'OESTE',
    'GARÇAS': 'PAMPULHA',
    'GLÓRIA': 'NOROESTE',
    'GOIÂNIA': 'NORDESTE',
    'GRAÇA': 'NORDESTE',
    'GRAJAÚ': 'OESTE',
    'GRANJA DE FREITAS': 'LESTE',
    'GRANJA WERNECK': 'NORTE',
    'GROTA': 'LESTE',
     'GROTINHA': 'NORDESTE',
    'GUANABARA': 'NORDESTE',
    'GUARANI': 'NORTE',
    'GUARATÃ': 'OESTE',
    'GUTIERREZ': 'OESTE',
    'HAVAÍ': 'OESTE',
    'HELIÓPOLIS': 'NORTE',
    'HORTO': 'LESTE',
    'HORTO FLORESTAL': 'LESTE',
    'IMBAÚBAS': 'OESTE',
    'INCONFIDÊNCIA': 'PAMPULHA',
    'INDAIÁ': 'PAMPULHA',
    'INDEPENDÊNCIA': 'BARREIRO',
    'IPÊ': 'NORDESTE',
    'IPIRANGA': 'NORDESTE',
    'ITAIPU': 'BARREIRO',
    'ITAPOÃ': 'PAMPULHA',
    'ITATIAIA': 'PAMPULHA',
    'JAQUELINE': 'NORTE',
    'JARAGUÁ': 'PAMPULHA',
    'JARDIM ALVORADA': 'PAMPULHA',
     'JARDIM AMÉRICA': 'OESTE',
    'JARDIM ATLÂNTICO': 'PAMPULHA',
    'JARDIM DO VALE': 'BARREIRO',
    'JARDIM DOS COMERCIÁRIOS': 'VENDA NOVA',
    'JARDIM FELICIDADE': 'NORTE',
     'JARDIM GUANABARA': 'NORTE',
    'JARDIM LEBLON': 'VENDA NOVA',
    'JARDIM MONTANHÊS': 'NOROESTE',
    'JARDIM SÃO JOSÉ': 'PAMPULHA',
    'JARDIM VITÓRIA': 'NORDESTE',
    'JARDINÓPOLIS': 'OESTE',
    'JATOBÁ': 'BARREIRO',
    'JOÃO ALFREDO': 'LESTE',
    'JOÃO PAULO II': 'BARREIRO',
    'JOÃO PINHEIRO': 'NOROESTE',
    'JONAS VEIGA': 'LESTE',
    'JULIANA': 'NORTE',
    'LAGOA': 'VENDA NOVA',
    'LAGOA DA PAMPULHA': 'PAMPULHA',
    'LAGOINHA': 'NOROESTE',
    'LAGOINHA LEBLON': 'VENDA NOVA',
    'LAJEDO': 'NORTE',
     'LARANJEIRAS': 'VENDA NOVA',
    'LEONINA': 'OESTE',
    'LETÍCIA': 'VENDA NOVA',
    'LIBERDADE': 'PAMPULHA',
     'LINDÉIA': 'BARREIRO',
    'LORENA': 'NOROESTE',
    'LOURDES': 'CENTRO-SUL',
    'LUXEMBURGO': 'CENTRO-SUL',
    'MADRE GERTRUDES': 'OESTE',
    'MADRI': 'NORTE',
    'MALA E CUIA': 'CENTRO-SUL',
    'MANACÁS': 'PAMPULHA',
    'MANGABEIRAS': 'CENTRO-SUL',
    'MANGUEIRAS': 'BARREIRO',
    'MANTIQUEIRA': 'VENDA NOVA',
    'MARAJÓ': 'OESTE',
    'MARAVILHA': 'OESTE',
    'MARÇOLA': 'CENTRO-SUL',
    'MARIA GORETTI': 'NORDESTE',
    'MARIA HELENA': 'VENDA NOVA',
    'MARIA TERESA': 'NORTE',
     'MARIA VIRGÍNIA': 'NORDESTE',
    'MARIANO DE ABREU': 'LESTE',
    'MARIETAI': 'BARREIRO',
    'MARIETA II': 'BARREIRO',
    'MARILÂNDIA': 'BARREIRO',
    'MARIQUINHAS': 'NORTE',
    'MARMITEIROS': 'NOROESTE',
     'MILIONÁRIOS': 'BARREIRO',
    'MINAS BRASIL': 'NOROESTE',
    'MINASCAIΧΑ': 'VENDA NOVA',
     'MINASLÂNDIA': 'NORTE',
    'MINEIRÃO': 'BARREIRO',
     'MIRAMAR': 'BARREIRO',
    'MIRANTE': 'NORTE',
    'MIRTES': 'NORDESTE',
     'MONSENHOR MESSIAS': 'NOROESTE',
    'MONTE AZUL': 'NORTE',
    'MONTE SÃO JOSÉ': 'CENTRO-SUL',
    'MORRO DOS MACACOS': 'NORDESTE',
    'NAZARÉ': 'NORDESTE',
    'NOSSA SENHORA DA APARECIDA': 'CENTRO-SUL',
    'NOSSA SENHORA DA CONCEIÇÃO': 'CENTRO-SUL',
    'NOSSA SENHORA DE FÁTIMA': 'CENTRO-SUL',
    'NOSSA SENHORA DO ROSÁRIO': 'CENTRO-SUL',
    'NOVA AMÉRICA': 'VENDA NOVA',
    'NOVA CACHOEIRINHA': 'NOROESTE',
    'NOVA CINTRA': 'OESTE',
    'NOVA ESPERANÇA': 'NOROESTE',
    'NOVA FLORESTA': 'NORDESTE',
     'NOVA GAMELEIRA': 'OESTE',
    'NOVA GRANADA': 'OESTE',
    'NOVA PAMPULHA': 'PAMPULHA',
    'NOVA SUISSA': 'OESTE',
     'NOVA VISTA': 'LESTE',
    'NOVO AARÃO REIS': 'NORTE',
    'NOVO GLÓRIA': 'NOROESTE',
    'NOVO OURO PRETO': 'PAMPULHA',
    'NOVO SANTA CECÍLIA': 'BARREIRO',
     'NOVO SÃO LUCAS': 'CENTRO-SUL',
    'NOVO TUPI': 'NORTE',
     'OESTE': 'OESTE',
    'OLARIA': 'BARREIRO',
    "OLHOS D'ÁGUA": 'OESTE',
    'OURO MINAS': 'NORDESTE',
     'OURO PRETO': 'PAMPULHA',
    'PADRE EUSTÁQUIO': 'NOROESTE',
    'PALMARES': 'NORDESTE',
    'PALMEIRAS': 'OESTE',
    'PANTANAL': 'OESTE',
    'PAQUETÁ': 'PAMPULHA',
     'PARAÍSO': 'LESTE',
    'PARQUE SÃO JOSÉ': 'OESTE',
    'PARQUE SÃO PEDRO': 'VENDA NOVA',
     'PAULO VI': 'NORDESTE',
     'PEDREIRA PRADO LOPES': 'NOROESTE',
    'PENHA': 'NORDESTE',
    'PETRÓPOLIS': 'BARREIRO',
     'PILAR': 'BARREIRO',
    'PINDORAMA': 'NOROESTE',
     'PINDURA SAIA': 'CENTRO-SUL',
    'PIRAJÁ': 'NORDESTE',
    'PIRATININGA': 'VENDA NOVA',
    'PIRINEUS': 'LESTE',
    'PLANALTO': 'NORTE',
     'POMPÉIA': 'LESTE',
    'PONGELUPE': 'BARREIRO',
    'POUSADA SANTO ANTÔNIO': 'NORDESTE',
    'PRADO': 'OESTE',
     'PRIMEIRO DE MAIΟ': 'NORTE',
     'PROVIDÊNCIA': 'NORTE',
    'RENASCENÇA': 'NORDESTE',
    'RIBEIRO DE ABREU': 'NORDESTE',
    'RIO BRANCO': 'VENDA NOVA',
    'SAGRADA FAMÍLIA': 'LESTE',
    'SALGADO FILHO': 'OESTE',
    'SANTA AMÉLIA': 'PAMPULHA',
    'SANTA BRANCA': 'PAMPULHA',
    'SANTA CECÍLIA': 'BARREIRO',
    'SANTA CRUZ': 'NORDESTE',
    'SANTA EFIGÊNIA': 'CENTRO-SUL',
     'SANTA HELENA': 'BARREIRO',
    'SANTA INÊS': 'LESTE',
    'SANTA ISABEL': 'CENTRO-SUL',
    'SANTA LÚCIA': 'CENTRO-SUL',
    'SANTA MARGARIDA': 'BARREIRO',
    'SANTA MARIA': 'OESTE',
    'SANTA MÔNICA': 'VENDA NOVA',
     'SANTA RITA': 'BARREIRO',
    'SANTA RITA DE CÁSSIA': 'CENTRO-SUL',
    'SANTA ROSA': 'PAMPULHA',
    'SANTA SOFIA': 'OESTE',
    'SANTA TEREZA': 'LESTE',
    'SANTA TEREZINHA': 'PAMPULHA',
    'SANTANA DO CAFEZAL': 'CENTRO-SUL',
    'SANTO AGOSTINHO': 'CENTRO-SUL',
    'SANTO ANDRÉ': 'NOROESTE',
    'SANTO ANTÔNIO': 'CENTRO-SUL',
     'SÃO BENEDITO': 'NORDESTE',
    'SÃO BENTO': 'CENTRO-SUL',
    'SÃO BERNARDO': 'NORTE',
    'SÃO CRISTÓVÃO': 'NOROESTE',
    'SÃO DAMIÃO': 'VENDA NOVA',
    'SÃO FRANCISCO': 'PAMPULHA',
    'SÃO FRANCISCO DAS CHAGAS': 'NOROESTE',
    'SÃO GABRIEL': 'NORDESTE',
     'SÃO GERALDO': 'LESTE',
    'SÃO GONÇALO': 'NORTE',
    'SÃO JOÃO': 'BARREIRO',
    'SÃO JOÃO BATISTA': 'VENDA NOVA',
    'SÃO JORGE I': 'OESTE',
    'SÃO JORGE II': 'OESTE',
    'SÃO JORGE III': 'OESTE',
     'SÃO JOSÉ': 'PAMPULHA',
    'SÃO LUCAS': 'CENTRO-SUL',
    'SÃO LUÍZ': 'PAMPULHA',
    'SÃO MARCOS': 'NORDESTE',
    'SÃO PAULO': 'NORDESTE',
    'SÃO PEDRO': 'CENTRO-SUL',
    'SÃO SALVADOR': 'NOROESTE',
     'SÃO SEBASTIÃO': 'NORDESTE',
    'SÃO TOMÁZ': 'NORTE',
    'SÃO VICENTE': 'LESTE',
    'SATÉLITE': 'NORTE',
     'SAUDADE': 'LESTE',
    'SAVASSI': 'CENTRO-SUL',
    'SENHOR DOS PASSOS': 'NOROESTE',
     'SERRA': 'CENTRO-SUL',
    'SERRA DO CURRAL': 'BARREIRO',
    'SERRA VERDE': 'VENDA NOVA',
    'SERRANO': 'PAMPULHA',
    'SILVEIRA': 'NORDESTE',
    'SION': 'CENTRO-SUL',
    'SOLAR DO BARREIRO': 'BARREIRO',
    'SOLIMÕES': 'NORTE',
    'SPORT CLUB': 'OESTE',
    'SUMARÉ': 'NOROESTE',
    'SUZANA': 'PAMPULHA',
    'TAQUARIL': 'LESTE',
    'TEIXEIRA DIAS': 'BARREIRO',
    'TIRADENTES': 'NORDESTE',
    'TIROL': 'BARREIRO',
    'TRÊS MARIAS': 'NORDESTE',
    'TREVO': 'PAMPULHA',
    'TÚNEL DE IBIRITÉ': 'BARREIRO',
    'TUPI A': 'NORTE',
    'TUPI B': 'NORTE',
    'UNIÃO': 'NORDESTE',
    'UNIDAS': 'VENDA NOVA',
    'UNIVERSITÁRIO': 'PAMPULHA',
    'UNIVERSO': 'VENDA NOVA',
    'URCA': 'PAMPULHA',
    'VALE DO JATOBÁ': 'BARREIRO',
     'VÁRZEA DA PALMA': 'VENDA NOVA',
    'VENDA NOVA': 'VENDA NOVA',
    'VENTOSA': 'OESTE',
    'VERA CRUZ': 'LESTE',
    'VILA AEROPORTO': 'NORTE',
    'VILA AEROPORTO JARAGUÁ': 'PAMPULHA',
     'VILA ANTΕΝΑ': 'OESTE',
    'VILA ANTENA MONTANHÊS': 'PAMPULHA',
    'VILA ÁTILA DE PAIVA': 'BARREIRO',
    'VILA BANDEIRANTES': 'CENTRO-SUL',
    'VILA BARRAGEM SANTA LÚCIA': 'CENTRO-SUL',
    'VILA BATIK': 'BARREIRO',
    'VILA BETÂNIA': 'OESTE',
    'VILA BOA VISTA': 'LESTE',
    'VILA CALAFATE': 'OESTE',
    'VILA CALIFORNIA': 'NOROESTE',
    'VILA CANTO DO SABIÁ': 'VENDA NOVA',
    'VILA CEMIG': 'BARREIRO',
    'VILA CLÓRIS': 'NORTE',
    'VILA COPACABANA': 'VENDA NOVA',
     'VILA COPASA': 'BARREIRO',
    'VILA COQUEIRAL': 'NOROESTE',
     'VILA DA AMIZADE': 'OESTE',
    'VILA DA ÁREA': 'LESTE',
    'VILA DA LUZ': 'NORDESTE',
    'VILA DA PAZ': 'NORDESTE',
    'VILA DAS OLIVEIRAS': 'NOROESTE',
    'VILA DE SÁ': 'NORDESTE',
    'VILA DIAS': 'LESTE',
    'VILA DO POMBAL': 'NORDESTE',
     'VILA DOS ANJOS': 'VENDA NOVA',
    'VILA ECOLÓGICA': 'BARREIRO',
    'VILA ENGENHO NOGUEIRA': 'PAMPULHA',
    'VILA ESPLANADA': 'NORDESTE',
    'VILA FORMOSA': 'BARREIRO',
    'VILA FUMEC': 'CENTRO-SUL',
    'VILA HAVAÍ': 'OESTE',
    'VILA INDEPENDÊNCIA I': 'BARREIRO',
    'VILA INDEPENDÊNCIA II': 'BARREIRO',
    'VILA INDEPENDÊNCIA IV': 'BARREIRO',
    'VILA INESTAN': 'NORDESTE',
    'VILA IPIRANGA': 'NORDESTE',
    'VILA JARDIM ALVORADA': 'PAMPULHA',
    'VILA JARDIM LEBLON': 'VENDA NOVA',
    'VILA JARDIM MONTANHÊS': 'PAMPULHA',
    'VILA JARDIM SÃO JOSÉ': 'PAMPULHA',
     'VILA MADRE GERTRUDES I': 'OESTE',
     'VILA MADRE GERTRUDES II': 'OESTE',
     'VILA MADRE GERTRUDES III': 'OESTE',
    'VILA MADRE GERTRUDES V': 'OESTE',
    'VILA MALOCA': 'NOROESTE',
    'VILA MANGUEIRAS': 'BARREIRO',
    'VILA MANTIQUEIRA': 'VENDA NOVA',
    'VILA MARIA': 'NORDESTE',
    'VILA MINASLÂNDIA': 'NORTE',
    'VILA NOSSA SENHORA APARECIDA': 'VENDA NOVA',
    'VILA NOSSA SENHORA DO ROSÁRIO': 'LESTE',
    'VILA NOVA': 'NORTE',
    'VILA NOVA CACHOEIRINHA I': 'NOROESTE',
    'VILA NOVA CACHOEIRINHA II': 'NOROESTE',
    'VILA NOVA CACHOEIRINHA IV': 'NORDESTE',
    'VILA NOVA DOS MILIONÁRIOS': 'BARREIRO',
    'VILA NOVA GAMELEIRA I': 'OESTE',
    'VILA NOVA GAMELEIRA II': 'OESTE',
    'VILA NOVA GAMELEIRA III':'OESTE',
    'VILA NOVA PARAÍSO':'OESTE',
    'VILA NOVO SÃO LUCAS':'CENTRO-SUL',
    'VILA OESTE': 'OESTE',
    'VILA OLHOS D\'ÁGUA': 'BARREIRO',
    'VILA OURO MINAS': 'NORDESTE',
    'VILA PAQUETÁ':'PAMPULHA',
    'VILA PARAÍSO':'LESTE',
    'VILA PARIS':'CENTRO-SUL',
    'VILA PETRÓPOLIS': 'BARREIRO',
    'VILA PILAR':'BARREIRO',
    'VILA PINHO':'BARREIRO',
    'VILA PIRATININGA':'BARREIRO',
    'VILA PIRATININGA VENDA NOVA':'VENDA NOVA',
    'VILA PRIMEIRO DE ΜΑΙΟ':'NORTE',
    'VILA PUC':'NOROESTE',
    'VILA REAL I':'PAMPULHA',
    'VILA REAL II':'PAMPULHA',
    'VILA RICA':'PAMPULHA',
    'VILA SANTA MÔNICA':'VENDA NOVA',
    'VILA SANTA ROSA':'PAMPULHA',
    'VILA SANTO ANTÔNIO':'PAMPULHA',
    'VILA SANTO ANTÔNIO BARROQUINHA':'PAMPULHA',
    'VILA SÃO DIMAS':'NORDESTE',
    'VILA SÃO FRANCISCO':'PAMPULHA',
    'VILA SÃO GABRIEL':'NORDESTE',
    'VILA SÃO GABRIEL JACUÍ':'NORDESTE',
    'VILA SÃO GERALDO':'LESTE',
    'VILA SÃO JOÃO BATISTA':'VENDA NOVA',
    'VILA SÃO PAULO':'NORDESTE',
    'VILA SÃO RAFAEL':'LESTE',
    'VILA SATÉLITE':'VENDA NOVA',
    'VILA SESC':'VENDA NOVA',
    'VILA SUMARÉ':'NOROESTE',
    'VILA SUZANA I': 'PAMPULHA',
    'VILA SUZANA II': 'PAMPULHA',
     'VILA TIROL': 'BARREIRO',
    'VILA TRINTA E UM DE MARÇO': 'NOROESTE',
    'VILA UNIÃO': 'LESTE',
    'VILA VERA CRUZ I': 'LESTE',
    'VILA VERA CRUZ II': 'LESTE',
    'VILA VISTA ALEGRE': 'OESTE',
    'VIRGÍNIA': 'OESTE',
    'VISTA ALEGRE': 'OESTE',
    'VISTA DO SOL': 'NORDESTE',
    'VITÓRIA': 'NORDESTE',
    'VITÓRIA DA CONQUISTA': 'BARREIRO',
    'XANGRI-LÁ': 'PAMPULHA',
    'XODÓ-MARIZE': 'NORTE',
    'ZILAH SPÓSITO': 'NORTE'

    }

     # Adicionando a coluna 'REGIÃO' com base no dicionário
    data['REGIÃO'] = data['BAIRRO'].map(mapeamento_regioes)

    # Substituindo valores NaN na coluna REGIÃO por "DESCONHECIDO"
    data['REGIÃO'] = data['REGIÃO'].fillna('DESCONHECIDO')

    # Aplicando One-Hot Encoding
    data = pd.get_dummies(data, columns=['REGIÃO'], prefix='REGIÃO')

    return data
    